### ISSUE TITLE
`mkl_fft` available via `conda`?

### ISSUE THREAD

**Issue by RemiLehe** [IntelPython/mkl_fft#1]
Hey, thanks a lot for making `mkl_fft` available!

One quick question: is the package already available on Intel's conda channel? I tried
```
conda install -c intel mkl_fft
```
but this failed...

Thanks in advance for your help!

**Comment by jakirkham** [comment]
It's in `conda-forge`.

ref: https://github.com/conda-forge/mkl_fft-feedstock

**Comment by oleksandr-pavlyk** [comment]
And it has also been available via `conda install -c intel mkl_fft`.
