### ISSUE TITLE
Single Precision FFT for Single Precision Input

### ISSUE THREAD

**Issue by michael-kuhlmann** [IntelPython/mkl_fft#10]
Could you check mkl_fft integration into numpy? When using anaconda/numpy with mkl_fft 1.0.1, the FFT returns single precision result for single precision input. But pip/numpy without mkl_fft returns double precision FFT for single precision input. It would be nice if numpy's FFT behaves the same with or without mkl_fft being installed (see https://github.com/ContinuumIO/anaconda-issues/issues/9550 and https://github.com/numpy/numpy/issues/11241 for toy example)

**Comment by oleksandr-pavlyk** [comment]
NumPy's own FFT code casts single precision array to a double precision array and then performs the FFT. It is done out of lack of support for FFT in single precision.

MKL's FFT has this support, it does not make sense to post process FFT result to upcast it to `np.double`.

If your code expects that FFT result be a double precision complex array, perhaps it makes sense to perform the type conversion in your application prior to the call to FFT.

**Comment by oleksandr-pavlyk** [comment]
Intending to close seeing that there is no counter-arguments presented.
