### ISSUE TITLE
HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

### ISSUE THREAD

**Issue by rootsmusic** [IntelPython/mkl_fft#107]
When I try to run `conda install -c intel mkl_fft`, it shows the error:
> Channels:
>  - intel
>  - conda-forge
>  - defaults
>
> Platform: win-64
> Collecting package metadata (repodata.json): failed
> 
> UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>
> 
> The channel is not accessible or is invalid.

**Comment by skapin** [comment]
yes, its down. i hope its note definitive

https://community.intel.com/t5/Intel-Integrated-Performance/Problems-installing-with-conda-HTTP-403-FORBIDDEN/td-p/1611876

https://community.intel.com/t5/oneAPI-Registration-Download/Disappearance-of-intel-conda-channel/td-p/1614250

**Comment by skapin** [comment]
Use this  


https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/conda.html#GUID-BAA00723-86B2-4E54-9343-E817171F8A39

**Comment by rootsmusic** [comment]
Thanks @skapin, I couldn't find Intel's feedstock on Github to open this issue.

**Comment by skapin** [comment]
But there is not all package.... like intel::numpy... for me, it's fucked up all my customer conda build and workflow.... this is so garbage ....

**Comment by oleksandr-pavlyk** [comment]
Since the README has been updated to use "-c https://software.repos.intel.com/python/conda" instead of "-c intel", I think this issue can be closed now.
