### ISSUE TITLE
Cannot import mkl_fft after manual build and install of v1.3.10 on W11

### ISSUE THREAD

**Issue by NairoDorian** [IntelPython/mkl_fft#113]
Hello I installed oneAPI BaseToolKit

I added the environment variables and manually installed v1.3.10 of mkl_fft using the setup.py install command 

No when I try to import mkl_fft in a python script in the venv I installed everything I get this error :

import mkl_fft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\MKL_FFT\venv\Lib\site-packages\mkl_fft\__init__.py", line 27, in <module>
    from ._pydfti import (fft, ifft, fft2, ifft2, fftn, ifftn, rfft, irfft,
ImportError: DLL load failed while importing _pydfti: The specified module could not be found.

I tried another version of python but it didn't solve my issue

Do you have any idea why it might not work ? 

I am desperate at figuring out to use the intel mkl fft or the ipp ftt, whatever is the fastest

**Comment by NairoDorian** [comment]
Even tried to use the Intel® Distribution for Python with 1.3.8 of mkl_fft, still cannot import it 
\venv\Lib\site-packages\mkl_fft\__init__.py", line 27
    from ._pydfti import (fft, ifft, fft2, ifft2, fftn, ifftn, rfft, irfft,
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mkl_fft._pydfti'

**Comment by oleksandr-pavlyk** [comment]
Could you please check if the advice from https://github.com/IntelPython/dpctl/issues/1745#issuecomment-2239474787 helps?

This should allow Python find MKL library DLLs as failure to find them trips `ModuleNotFoundError` or `ImportError`. 

Additionally, please check that `\venv\Lib\site-packages\mkl_fft` folder does contains the `_pydfti.*.pyd` file.

**Comment by NairoDorian** [comment]
now i get this error : 

import mkl_fft
  File "C:\Program Files\Python311\Lib\site-packages\mkl_fft\__init__.py", line 31, in <module>
    import mkl_fft.interfaces
  File "C:\Program Files\Python311\Lib\site-packages\mkl_fft\interfaces\__init__.py", line 27, in <module>
    from . import scipy_fft
  File "C:\Program Files\Python311\Lib\site-packages\mkl_fft\interfaces\scipy_fft.py", line 27, in <module>
    from .._scipy_fft_backend import *
  File "C:\Program Files\Python311\Lib\site-packages\mkl_fft\_scipy_fft_backend.py", line 29, in <module>
    import mkl
ModuleNotFoundError: No module named 'mkl'

**Comment by oleksandr-pavlyk** [comment]
Please make sure that `mkl-service` package is installed, and you have `\venv\Lib\site-packages\mkl` folder with files in it.

**Comment by NairoDorian** [comment]
This is working now, thank you

**Comment by NairoDorian** [comment]
This is working now, thank you
