### ISSUE TITLE
Getting ValueError: Internal error in both OS X and CentOS, with anaconda, python 3.6, mkl 1.0.6, numpy 1.15.1.

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/mkl_fft#24]
Doing scipy.signal.fftconvolve: 
```
import numpy as np
from scipy.signal import fftconvolve
d1 = np.random.rand(18768768)
d2 = np.random.rand(15243648)
xcraw = fftconvolve(d1, d2, mode='full')
```

leads to:
```
/Users/<user>/anaconda3/envs/py36/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py:1044: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.rfftn_numpy(a, s, axes)
Traceback (most recent call last):
  File "/Users/<user>/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-98737a11a4f0>", line 1, in <module>
    xcraw = fftconvolve(d1, d2, mode='full')
  File "/Users/<user>/anaconda3/envs/py36/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 391, in fftconvolve
    sp1 = np.fft.rfftn(in1, fshape)
  File "/Users/<user>/anaconda3/envs/py36/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py", line 1044, in rfftn
    output = mkl_fft.rfftn_numpy(a, s, axes)
  File "mkl_fft/_pydfti.pyx", line 834, in mkl_fft._pydfti.rfftn_numpy
  File "mkl_fft/_pydfti.pyx", line 588, in mkl_fft._pydfti.rfft_numpy
  File "mkl_fft/_pydfti.pyx", line 504, in mkl_fft._pydfti._rc_fft1d_impl
ValueError: Internal error occurred, with status=-1
```

Numpy config is:
```
(py36) [kime9@l-1-01 AudVidSync]$ python -c "import numpy; print(numpy.show_config())"
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/kime9/anaconda3/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/kime9/anaconda3/envs/py36/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/kime9/anaconda3/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/kime9/anaconda3/envs/py36/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/kime9/anaconda3/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/kime9/anaconda3/envs/py36/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/kime9/anaconda3/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/kime9/anaconda3/envs/py36/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/kime9/anaconda3/envs/py36/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/kime9/anaconda3/envs/py36/include']
None
```

I get the same error for:
`noverlap = fftconvolve(np.ones(d1), np.ones(d2), mode='full')`

Taking @oleksandr-pavlyk's advice and doing 
`np.fft.restore_all()`
works around the error.

Is this worth opening a ticket, or am I doing something wrong? Am I describing this in a way that is useful?

_Originally posted by @kusanagee in https://github.com/IntelPython/mkl_fft/issues/11#issuecomment-423220641_

**Comment by oleksandr-pavlyk** [comment]
Per @kusanagee [comment](https://github.com/IntelPython/mkl_fft/issues/11#issuecomment-423234140) in #11 the problem is reproducible in version 1.0.6 as well.

**Comment by oleksandr-pavlyk** [comment]
@kusangee It appears the error represents a genuine issue in MKL, which I have communicated to the MKL team, and they are trying to get the fix into the MKL 2019 update 1. 

A better error reporting in mkl_fft is in order though, using `DftiErrorMessage` (see [MKL developer reference](https://software.intel.com/en-us/mkl-developer-reference-c-dftierrormessage#A2F60411-84FC-42D5-94A2-F863A056BEEC)), so I'll keep the ticket open to do just that.

**Comment by oleksandr-pavlyk** [comment]
@kusanagee I had a word that the underlying issue in MKL has been fixed, and will appear in MKL 2019 update 2.

**Comment by oleksandr-pavlyk** [comment]
The issue is not fixed in MKL 2019.2, but is confirmed as fixed in the forthcoming MKL 2019.3

**Comment by tjb900** [comment]
@oleksandr-pavlyk Thanks for the help so far.  Are you able to advise exactly what the issue is in MKL?  Can it be worked around by e.g. choosing transform lengths carefully?

**Comment by oleksandr-pavlyk** [comment]
@tjb900 Intel (R) MKL has optimized kernels for [specific list of small primes](https://software.intel.com/en-us/articles/fft-length-and-layout-advisor). I suppose choosing length as a products of powers of these primes would work around this problem. Intel (R) MKL 2019.3 should be released soon though.

**Comment by oleksandr-pavlyk** [comment]
Intel(R) MKL 2019 update 3 conda package is available now: https://anaconda.org/intel/mkl

You can upgrade mkl in your conda environment via `conda install -c intel mkl=2019.3`.

**Comment by oleksandr-pavlyk** [comment]
Closing the issue now.
