### ISSUE TITLE
FutureWarning message for non-tuple multidimensional indexing

### ISSUE THREAD

**Issue by claudiodsf** [IntelPython/mkl_fft#25]
I started getting a `FutureWarning` when performing certains `rfft` with mkl_fft via numpy.

Here is a simple code that produces the warning:
```python
>>> import numpy as np
>>> from mkl_fft import rfft_numpy
>>> rfft_numpy(np.zeros((2, 1)), n=2)
__main__:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])
```

Here's my setup:
- Python 3.6.6
- numpy 1.15.1
- mkl_fft 1.0.4

(via anaconda on macOS)

**Comment by oleksandr-pavlyk** [comment]
@claudiodsf Thank you for reporting the issue. It has been fixed in mkl_fft 1.0.6 which is available from conda-forge, but not from anaconda's default channel. @msarahan, who should I ping to get the latest version of mkl_fft available on anaconda default channel?

**Comment by claudiodsf** [comment]
Thanks for the quick reply! Feel free to close this issue, then.

**Comment by claudiodsf** [comment]
mkl_fft 1.0.6 just landed on the default anaconda channel:

```
➜  ~ conda list mkl_fft --show-channel-urls
# packages in environment at /Users/claudio/anaconda3:
#
# Name                    Version                   Build  Channel
mkl_fft                   1.0.6            py36hb8a8100_0    defaults
```

I confirm that this version fixes the issues, so I close it.

Thanks!
