### ISSUE TITLE
Pip version older than conda version

### ISSUE THREAD

**Issue by blalterman** [IntelPython/mkl_fft#36]
See conda: https://anaconda.org/conda-forge/mkl_fft
Pypi: https://pypi.org/project/mkl-fft/

**Comment by carsen-stringer** [comment]
I second this, could you please update the pip too to be compatible with numpy1.16? Thanks for this great package!

**Comment by emigre459** [comment]
I upvote this too, I'm having trouble using it to deploy a heroku web app due to a mismatch with the pip version vs. conda version. Thank you for all your contributions!

**Comment by juskuz** [comment]
Up.
Could you update the package on pypi?

**Comment by PhilLab** [comment]
@oleksandr-pavlyk Is the pypi update something which is planned?

**Comment by ngupta23** [comment]
We are facing the same issue with the pip version. Would it be possible to upgrade the pip version?

**Comment by Vyacheslav-Smirnov** [comment]
Package versions on Anaconda and Pypi were aligned:
https://anaconda.org/conda-forge/mkl_fft
https://anaconda.org/conda-forge/mkl_fft
