### ISSUE TITLE
Warning: Mapping new ns to old ns and emulator stopping abruptly

### ISSUE THREAD

**Issue by debasissil-python** [IntelPython/mkl_fft#63]
After upgrading to Arctic Fox , I am getting the following errors, even though the emulator is running but sometimes stopping abruptly. What is this error ? How can I get rid of this ?

I am using the following as copied from` cmd `:

  ```
  > C:\Users\Debasis>flutter doctor Doctor summary (to see all details,
    > run flutter doctor -v): [√] Flutter (Channel stable, 2.2.3, on
    > Microsoft Windows [Version 10.0.19042.1165], locale en-IN) [√] Android
    > toolchain - develop for Android devices (Android SDK version 31.0.0)
    > [√] Chrome - develop for the web [√] Android Studio [√] Connected
    > device (2 available)

• No issues found !
```

The Error :

`Launching lib\main.dart on sdk gphone x86 in debug mode... Running Gradle task 'assembleDebug'... Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01 Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01 Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01 Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01 Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01 √ Built build\app\outputs\flutter-apk\app-debug.apk. Installing build\app\outputs\flutter-apk\app.apk... Debug service listening on ws://127.0.0.1:57467/XzCZTOeqyQs=/ws Syncing files to device sdk gphone x86...`

![The Issue](https://user-images.githubusercontent.com/70312792/129511543-1d767e6b-edc0-4da4-b042-077947abafab.png)
![SDK Platforms](https://user-images.githubusercontent.com/70312792/129511570-2ad5f97c-c1aa-4069-98e9-c4c1ac696906.png)
![SDK Tools](https://user-images.githubusercontent.com/70312792/129511617-3235e390-da83-415a-8328-0f09e0bdf851.png)

**Comment by oleksandr-pavlyk** [comment]
I fail to see how this is related to `mkl_fft` Python package this is filed against.

**Comment by debasissil-python** [comment]
Sorry this was wrongly posted here..
