### ISSUE TITLE
Confusing results from FFT

### ISSUE THREAD

**Issue by entelecheia1963** [IntelPython/mkl_fft#68]
This is a cross post from numpy/numpy as advisied by those guys ( https://github.com/numpy/numpy/issues/20113 )

Essentially this: Computing an FFT of a 1kHz sin wave recorded at 44100 samples per second. Sample length 1024. I am expecting to see two peaks in the spectrum at about bin 23 and 1002.  Instead I am seeing a strange, 'oscillating' spectrum:
![1kHz sin spectrum 15-10](https://user-images.githubusercontent.com/42785164/137631091-a008f5be-ce90-4508-93fe-cb7e2ce6df47.png)

Code to replicate is below, and source data-file (including the results I get) attached (I had to attach the .npz file within a .zip file as github won't let me upload .npz)

[FFT test data.zip](https://github.com/IntelPython/mkl_fft/files/7360064/FFT.test.data.zip)

```
import numpy as np
import matplotlib.pyplot as plt

fs = 44100

myData = np.load("FFT test data.npz")
print(myData['theSignal'])

theSignal = myData['theSignal']          # 1kx sin wav recorded at 44100 samples / sec
theFFT = myData['theFFT']                # FFT calculated on my machine using numpy
theAbs = myData['theAbs']                # Absolute value of FFT as caclulated on my machine

newFFT = np.fft.fft(theSignal)           # Fresh computation of FFT for caomparison
newAbs = np.abs(newFFT)

# Calculate the axis for plotting the signal
xAxis = [(x / fs) for x in range(0, theSignal.size)]         # Create a real-time x axis 
lastX = xAxis[len(xAxis) - 1]
maxY = np.amax(theSignal)
minY = np.amin(theSignal)
xfreq = np.fft.fftfreq(newFFT.size, 1/fs)  # calculates the frequencies in the center of each bin in the output of fft(). 


# Now plot the results
fig,ax = plt.subplots(2)

# Plot the oscillascope
ax[0].set_xlim([0,lastX])
ax[0].set_ylim([minY, maxY])
ax[0].set_xlabel('Time (s)')
ax[0].set_ylabel('Amplitude')
ax[0].set_title('Oscillascope')

ax[0].plot(xAxis, theSignal)

# Plot the frequency spectrum
ax[1].set_xlim([np.amin(xfreq), np.amax(xfreq)])
ax[1].set_ylim([np.amin(newAbs), np.amax(newAbs)])
ax[1].set_xlabel('Frequency (Hz)')
ax[1].set_ylabel('Energy')
ax[1].set_title('Spectrum')
ax[1].plot(xfreq, newAbs)

plt.show()
```

**Comment by oleksandr-pavlyk** [comment]
Closing given that the issue on the numpy issue tracker has been closed.
