### ISSUE TITLE
Consider removing cython from install_requires for setup.py used in conda recipe

### ISSUE THREAD

**Issue by kalefranz** [IntelPython/mkl_fft#7]
See https://github.com/AnacondaRecipes/aggregate/issues/53

**Comment by gabriellima** [comment]
Gentlemen, any update on this issue?

**Comment by oleksandr-pavlyk** [comment]
OK. If I remove `cython` from `install_requires`, how should I indicate to pip that `cython` may be needed for building the package?

**Comment by kalefranz** [comment]
Yeah I'm not sure.  Maybe a good discussion for distutils-sig?

Found this: https://github.com/pypa/pip/issues/2381#issuecomment-72002695

**Comment by oleksandr-pavlyk** [comment]
Fixed with PR #16.
