### ISSUE TITLE
setup.py uses numpy.distutils, which has been removed as of numpy 1.25

### ISSUE THREAD

**Issue by cbouss** [IntelPython/mkl_fft#87]
setup.py uses numpy.distutils, which has been removed as of numpy 1.25. 
This prevents python 3.12 builds.

**Comment by oleksandr-pavlyk** [comment]
`mkl_fft` v1.3.7 resolves this by transitioning away from `np.distutils`

**Comment by cbouss** [comment]
Hello, and thank you for the quick response.

np.distutils is still being used here: https://github.com/IntelPython/mkl_fft/blob/master/setup.py#L34
This is an issue as numpy.distutils is not available in numpy 1.25 python 3.12 builds.

As a minimal change, you could include a copy of https://github.com/numpy/numpy/blob/v1.25.2/numpy/distutils/conv_template.py to be used within setup.py

**Comment by oleksandr-pavlyk** [comment]
I am confused, since the file is present in NumPy sources: https://github.com/numpy/numpy/blob/maintenance/1.25.x/numpy/distutils/conv_template.py#L281

How can I get Python 3.12 binaries to experiment with this?
